### PR TITLE
remove white noise

### LINKED ISSUE #267: `--help` print white noise
After test, kingpin v2 always add a blank(marked as [ ]) when comment of flag change line:
```
      --gcloudtrace.project=GCLOUDTRACE.PROJECT[ ]
                                  GCP project to send Google Cloud Trace tracings
                                  to. If empty, tracing will be disabled.
```

### PR DESCRIPTION
**Pull request by daixiang0**
Fix #267 

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@alecthomas hi, mind have a look?

**Comment by daixiang0** [comment]
@alecthomas hi, mind have a look?

**Comment by alecthomas** [comment]
I think this is probably unnecessary, just for a space at the end of the line, but thanks for the PR.

**Comment by daixiang0** [comment]
@alecthomas It could be better, since i saw some project use help info to auto generate docs.

**Pull request closed without merging**
