### PR TITLE
Complete the last argument if not matching a hint

### PR DESCRIPTION
**Pull request by MiLk**
Instead of stopping the completion when there is a value for an
argument, try to verify if the value is matching one of the valid
option. If it's not matching, try to suggest all options starting by the
entered value.

Hopefully it should address https://github.com/alecthomas/kingpin/issues/159

### CODE REVIEW

**Comment by percona-csalguero** [comment]
It is a really good idea. I just would like to include tests.

**Comment by MiLk** [comment]
I've added tests and fixed some edge cases.

@alecthomas Is there anything preventing this to be merged?

**Comment by zippoxer** [comment]
Is there any update on this?

I'm using MiLK's fork because this is an important feature for me.

**Comment by alecthomas** [comment]
I honestly have no idea why I didn't merge this, sorry :(

**Pull request merged**
