### PR TITLE
Add codecov.io

### PR DESCRIPTION
**Pull request by gliptak**
Here is the link to my branch https://codecov.io/gh/gliptak/kingpin/branch/codecov1

### CODE REVIEW

**Comment by alecthomas** [comment]
In theory I like automated code coverage tools, but I find the GitHub integration waay too spammy. Thanks for the PR, but until that is fixed somehow, I don't really want to include it.

**Comment by gliptak** [comment]
@alecthomas Which part of the integration you see being spammy?

**Comment by alecthomas** [comment]
Commenting whenever a commit is pushed.

**Comment by gliptak** [comment]
Yes, I do see an extra email on the first build, and none after. You might have some different settings.

**Comment by alecthomas** [comment]
I'm not talking about this PR specifically. I'm talking about every PR. Every commit to every PR triggers coverage update mails. This is based on what I experienced in other projects.

**Pull request closed without merging**
