### PR TITLE
Remove ineffectual assignments in tests

### PR DESCRIPTION
**Pull request by muesli**
Don't assign a value to err if we don't end up checking it.

### CODE REVIEW

**Comment by alecthomas** [comment]
Can you consolidate these into one PR?

**Comment by muesli** [comment]
What exactly do you mean?

**Comment by alecthomas** [comment]
I mean rather than opening multiple PRs, just open one and put all the changes into it.

**Comment by alecthomas** [comment]
Also these aren't exactly ineffectual, they also serve to prevent errcheck from warning.

**Comment by muesli** [comment]
Sorry, I tried to group them into logical pieces, hoping it makes it easier to review and argue about changes. Case in point, you couldn't have rejected this particular change without rejecting the other changes as well. Anyway, whatever you prefer.

I guess it should assign `_, _ = app.Parse(...)` then?

**Comment by alecthomas** [comment]
Yeah that is even better!

**Pull request closed without merging**
