### PR TITLE
Bash completion

### PR DESCRIPTION
**Pull request by rgbkrk**
Initial implementation of #75. This only provides the top level commands to an application.

### CODE REVIEW

**Comment by rgbkrk** [comment]
[Helpful bits as I work out the rest](http://www.debian-administration.org/article/317/An_introduction_to_bash_completion_part_2). I'm... also learning go templates so you'll have to bear with me. :wink:

**Comment by alecthomas** [comment]
Thanks for this. It looks like it doesn't support flags or subcommands yet? If that's the case I think I'll hold off merging until it's complete.

**Comment by plalloni** [comment]
Great contribution! I has been wishing (and not finding available time slots for implementing) this for a long time.

**Comment by rgbkrk** [comment]
I've got a simpler and more fully featured version of this template that I've been working with and hopefully I'll be able to make it generic enough for this PR soon.

**Comment by alecthomas** [comment]
👍

**Comment by alecthomas** [comment]
Any progress on this? It would be great to get it in!

**Comment by rgbkrk** [comment]
Haven't been able to come back to it at the degree you want just yet. Would you be ok if we start with small incremental changes towards the full template we want?

**Comment by alecthomas** [comment]
Yeah, I think so. If the current code works at least partially, let's get it in.

**Comment by alecthomas** [comment]
Any news on this? It would be awesome to have.

**Comment by nickw444** [comment]
Take a look at #99, I've opened a PR to add deeper bash completion support.

**Comment by rgbkrk** [comment]
Awesome, thanks @nickw444

**Pull request closed without merging**
