### PR TITLE
Switch to text/template from Go 1.6

### PR DESCRIPTION
**Pull request by petercolberg**
The text/template package now supports whitespace trimming.

https://golang.org/doc/go1.6#template

### CODE REVIEW

**Comment by alecthomas** [comment]
Brilliant, thanks!

**Comment by petercolberg** [comment]
The merge commit 7d8d008 is no longer in the v3 branch. Did you rebase the branch onto v2/master?

Could you restore v3 to 7d8d008, and then merge bug fixes from v2/master (instead of rebasing)?

That will preserve the history attached to github pull requests and issues.

**Comment by petercolberg** [comment]
Further this seems a good time to rename master→v2 and v3→master (after merging master into v3 7d8d008), following the common convention that the master branch is the active development branch.

**Comment by alecthomas** [comment]
@petercolberg Your changes are in [v3](https://github.com/alecthomas/kingpin/commits/v3). And no, development won't be on master, it will be on v3-unstable. Too many people import master directly to be constantly merging breaking changes.

**Pull request merged**
