### PR TITLE
Flags mimic bool

### PR DESCRIPTION
**Pull request by sakateka**
Hi!
I have an idea how to add flags similar to Booleans, but taking optional values.
I also figured out how to make `isSetByUser` posible for users.
I implemented this idea and use it in my application.
But when implementing I did not understand how to set the default value correctly and used a dirty hack :-)
If these flags are interesting, I can try to make the proper setting of default values.

### CODE REVIEW

**Comment by alecthomas** [comment]
Hello. I guess I'm not sure what you're referring to. Can you show me an example?

**Comment by sakateka** [comment]
A good example is the lsof utility
If you run it with the `-i` option, it will show all network connections
`lsof -i`
If you pass an optional filter to `-i` like this `:22` then only ssh connections will be shown
`lsof -i :22`
If run without the `-i` option, then all open files will be shown, including network connections
`lsof`

My example, I want to implement the `-t` flag, which will add counting timings to a given field in the log.
If the user did not call the `-t` option, then do not count the timings.
If the user simply passed `-t` then the default timings are` request_time`
If the user passed the argument for `-t`, then count the timings specified by the user
For example, `-t ssl` will count the timings for the` ssl_handshake_time` field

**Comment by alecthomas** [comment]
The problem with this is how do you differentiate between an optional parameter to a flag, and a positional argument? This works for lsof because it does not support positional arguments.

eg. `command -i <param> <arg>` vs. `command -i <arg>` vs. `command -i <param>`

**Comment by sakateka** [comment]
Yes, it's a problem.
I remove all positional arguments from the command line, then call `kingpin.MustParse` and therefore my app behaves like losf.

As an option, the user should be aware of the problem and start the app like this `command <args> -i`
The documentation should clarify this point.
Or user can do so, specify an option with an empty value of `-i=` and after the space specify arguments, in this case `-i` should get the default value
`command -i=    args`
All these are workarounds that do not add simplicity :-(
It seems to me that clarification in the documentation is the most correct way.

**Comment by alecthomas** [comment]
There's also the issue of ambiguity with combined short flags, eg. `-i` and `-j` can be combined as `-ij`.

I don't think there's any way to support this that's reasonable, sorry :(

**Comment by sakateka** [comment]
I remembered the second part of my plan. )
There is still useful functionality that you can add here, it's `IsSetByUser`method
It will look like this.
```
app.Flag("timings", "Count timings").Short ('t').
    IsSetByUser(&args.TimingsSetByUser).Default ("up").StringVar(&args.Timings)
```

**Comment by alecthomas** [comment]
I didn't quite understand what problem that solved?

**Comment by sakateka** [comment]
If the flag have the default value (or not even), the variable will always be set to the default value or to the value provided by the user.
If there is a default value I want to know whether the user has set it (suddenly it has set a default value) or whether it is set by parser.
I've seen questions about this functionality, not sure what's in this project))

**Comment by matteopic** [comment]
I agree with @sakateka.
I have a case with a user that set a flag and my application records that setting.
When user start the application again, I would let him to omit that flag and use previous value as default, but currently I don't know how I can do that.

**Comment by sakateka** [comment]
pflag has this functionality https://github.com/spf13/pflag#setting-no-option-default-values-for-flags

**Pull request closed without merging**
